import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

export interface Word {
  data: string[]
}

export const randomWordApiSlice = createApi({
  // when we attach this to the store where are we storing it?
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({
    baseUrl: 'https://random-word-api.herokuapp.com/',
  }), 
  endpoints: builder => {
    // endpoint definitions generated by the builder
    return {
      fetchWord: builder.query<Word[], number | void>({
        // while endpoint will we hit
        query() {
          return `/word`
        }
      })
    }
  }
})

export const { useFetchWordQuery, useLazyFetchWordQuery } = randomWordApiSlice